---
- name: Provision and configure EC2 instance for Flask web app
  hosts: centos
  become: yes
  vars:
    flask_app_dir: /home/centos/flask-web-app
    flask_app_port: 5000

  tasks:
    - name: Update package cache
      yum:
        name: '*'
        update_cache: yes

    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - git

    - name: Clone Flask web app repository
      git:
        repo: https://github.com/joshkr1/flask-web-app.git
        dest: "{{ flask_app_dir }}"
        version: main

    # Additional tasks go here

